/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas5_individu_pbo11;

import java.awt.Color;

/**
 *
 * @author User
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLoginCreate = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        panelRegister = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        btnCreateReg = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnReset = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        menuPilihan = new javax.swing.JPanel();
        Profile = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        menu1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        menu3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        menu4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        About = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        welcome = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        bgMenu6 = new javax.swing.JLabel();
        tampilMenu1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        bgMenu1 = new javax.swing.JLabel();
        tampilMenu2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jTextField11 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel56 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        bgMenu2 = new javax.swing.JLabel();
        tampilMenu3 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel61 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        bgMenu3 = new javax.swing.JLabel();
        tampilMenu4 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel69 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        bgMenu4 = new javax.swing.JLabel();
        tampilAbout = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        bgAbout = new javax.swing.JLabel();
        bgMenu = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 600));

        panelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLoginMouseEntered(evt);
            }
        });
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("LOGIN");
        panelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Username");
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));

        jTextField1.setBackground(new java.awt.Color(204, 204, 255, 50));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelLogin.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 190, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("HELLO");
        panelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 255, 50));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelLogin.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 190, -1));

        btnLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLoginMouseMoved(evt);
            }
        });
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });

        jLabel5.setText("LOGIN");

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, 30));

        jLabel7.setText("OR");
        panelLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        btnLoginCreate.setBackground(new java.awt.Color(204, 204, 204));
        btnLoginCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginCreateMouseExited(evt);
            }
        });

        jLabel6.setText("CREATE");

        javax.swing.GroupLayout btnLoginCreateLayout = new javax.swing.GroupLayout(btnLoginCreate);
        btnLoginCreate.setLayout(btnLoginCreateLayout);
        btnLoginCreateLayout.setHorizontalGroup(
            btnLoginCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(btnLoginCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLoginCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnLoginCreateLayout.setVerticalGroup(
            btnLoginCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(btnLoginCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnLoginCreateLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelLogin.add(btnLoginCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 70, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login.png"))); // NOI18N
        panelLogin.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 100, -1));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background1.jpg"))); // NOI18N
        panelLogin.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Register");
        panelRegister.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("NAME");
        panelRegister.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("EMAIL");
        panelRegister.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("PHONE");
        panelRegister.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("PASSWORD");
        panelRegister.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("CONFIRM PASSWORD");
        panelRegister.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204, 50));
        panelRegister.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 200, -1));

        jPasswordField2.setBackground(new java.awt.Color(204, 204, 204, 50));
        panelRegister.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 200, -1));

        jPasswordField3.setBackground(new java.awt.Color(204, 204, 204, 50));
        panelRegister.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 200, -1));

        jTextField4.setBackground(new java.awt.Color(204, 204, 204, 50));
        panelRegister.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, -1));

        jTextField5.setBackground(new java.awt.Color(204, 204, 204, 50));
        panelRegister.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 200, -1));

        btnCreateReg.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateRegMouseExited(evt);
            }
        });

        jLabel16.setText("CREATE");

        javax.swing.GroupLayout btnCreateRegLayout = new javax.swing.GroupLayout(btnCreateReg);
        btnCreateReg.setLayout(btnCreateRegLayout);
        btnCreateRegLayout.setHorizontalGroup(
            btnCreateRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(btnCreateRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCreateRegLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnCreateRegLayout.setVerticalGroup(
            btnCreateRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(btnCreateRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCreateRegLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelRegister.add(btnCreateReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 60, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setText("CREATE YOUR ACCOUNT");
        panelRegister.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });

        jLabel15.setText("Back");

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnBackLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnBackLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelRegister.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 60, 20));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/register.png"))); // NOI18N
        panelRegister.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(153, 204, 255, 50));
        jCheckBox1.setText("I Agree the therms for services");
        panelRegister.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetMouseExited(evt);
            }
        });

        jLabel27.setText("RESET");

        javax.swing.GroupLayout btnResetLayout = new javax.swing.GroupLayout(btnReset);
        btnReset.setLayout(btnResetLayout);
        btnResetLayout.setHorizontalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnResetLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnResetLayout.setVerticalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnResetLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelRegister.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 60, 20));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background1.jpg"))); // NOI18N
        panelRegister.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHomeMouseEntered(evt);
            }
        });
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPilihan.setBackground(new java.awt.Color(204, 204, 204, 50));
        menuPilihan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Profile.setBackground(new java.awt.Color(153, 204, 255));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile.png"))); // NOI18N

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel25)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addContainerGap())
        );

        menuPilihan.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 130));

        menu1.setBackground(new java.awt.Color(204, 204, 204));
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu1MouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Menu 1");

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPilihan.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 50));

        menu2.setBackground(new java.awt.Color(204, 204, 204));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu2MouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Menu 2");

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        menu2Layout.setVerticalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPilihan.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 50));

        menu3.setBackground(new java.awt.Color(204, 204, 204));
        menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu3MouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Menu 3");

        javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
        menu3.setLayout(menu3Layout);
        menu3Layout.setHorizontalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        menu3Layout.setVerticalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPilihan.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 50));

        menu4.setBackground(new java.awt.Color(204, 204, 204));
        menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu4MouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Menu 4");

        javax.swing.GroupLayout menu4Layout = new javax.swing.GroupLayout(menu4);
        menu4.setLayout(menu4Layout);
        menu4Layout.setHorizontalGroup(
            menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        menu4Layout.setVerticalGroup(
            menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPilihan.add(menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, 50));

        About.setBackground(new java.awt.Color(204, 204, 204));
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("About");

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AboutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AboutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel24)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPilihan.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 140, 50));

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Logout");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menuPilihan.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 140, 50));

        panelHome.add(menuPilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 530));

        welcome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                welcomeMouseEntered(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setText("Welcome");

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel85.setText("Aplikasi ini dibuat untuk memenuhi tugas mata kuliah PBO ");

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel86.setText("Bila ada saran, masukan, atau kritik, silahkan hubungi saya melalui kontak yang ada di menu About");

        bgMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg4.jpg"))); // NOI18N

        javax.swing.GroupLayout welcomeLayout = new javax.swing.GroupLayout(welcome);
        welcome.setLayout(welcomeLayout);
        welcomeLayout.setHorizontalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeLayout.createSequentialGroup()
                        .addComponent(jLabel86)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeLayout.createSequentialGroup()
                        .addComponent(jLabel85)
                        .addGap(136, 136, 136))))
            .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(welcomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgMenu6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        welcomeLayout.setVerticalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel14)
                .addGap(28, 28, 28)
                .addComponent(jLabel85)
                .addGap(32, 32, 32)
                .addComponent(jLabel86)
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(welcomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgMenu6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelHome.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 530));

        tampilMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tampilMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tampilMenu1MouseExited(evt);
            }
        });
        tampilMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Menu 1 Perhitugan Bangun Ruang ");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 11, -1, -1));

        jLabel33.setBackground(new java.awt.Color(204, 255, 255));
        jLabel33.setForeground(new java.awt.Color(204, 255, 255));
        jLabel33.setText("BOLA");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, 10));

        jLabel34.setBackground(new java.awt.Color(204, 255, 255));
        jLabel34.setForeground(new java.awt.Color(204, 255, 255));
        jLabel34.setText("Jari-jari");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 55, -1));

        jLabel35.setBackground(new java.awt.Color(204, 255, 255));
        jLabel35.setForeground(new java.awt.Color(204, 255, 255));
        jLabel35.setText("KERUCUT");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel36.setBackground(new java.awt.Color(204, 255, 255));
        jLabel36.setForeground(new java.awt.Color(204, 255, 255));
        jLabel36.setText("Jari-jari");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 130, 10));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 55, -1));

        jLabel37.setBackground(new java.awt.Color(204, 255, 255));
        jLabel37.setForeground(new java.awt.Color(204, 255, 255));
        jLabel37.setText("Tinggi");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 20));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 55, -1));

        jLabel38.setBackground(new java.awt.Color(204, 255, 255));
        jLabel38.setForeground(new java.awt.Color(204, 255, 255));
        jLabel38.setText("TABUNG");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 130, 10));

        jLabel39.setBackground(new java.awt.Color(204, 255, 255));
        jLabel39.setForeground(new java.awt.Color(204, 255, 255));
        jLabel39.setText("Jari-jari");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 20));

        jLabel40.setBackground(new java.awt.Color(204, 255, 255));
        jLabel40.setForeground(new java.awt.Color(204, 255, 255));
        jLabel40.setText("Tinggi");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 520, 10));

        jLabel41.setBackground(new java.awt.Color(204, 255, 255));
        jLabel41.setForeground(new java.awt.Color(204, 255, 255));
        jLabel41.setText("Output Hasil Bola :");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 150, 120));

        jLabel42.setForeground(new java.awt.Color(204, 255, 255));
        jLabel42.setText("Output Hasil Kerucut");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 150, 120));

        jLabel43.setForeground(new java.awt.Color(204, 255, 255));
        jLabel43.setText("Output Hasil Tabung");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 150, 120));

        jLabel87.setText("HITUNG");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel87)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel87)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, 30));

        jLabel88.setText("HITUNG");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel88)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel88)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, -1));

        jLabel89.setText("HITUNG");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel89)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel89)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));
        jPanel1.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 55, -1));
        jPanel1.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 55, -1));

        tampilMenu1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 580, 470));

        bgMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg4.jpg"))); // NOI18N
        tampilMenu1.add(bgMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelHome.add(tampilMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 530));

        tampilMenu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel44.setText("Menu 2 Perhitugan Bangun Datar ");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 11, -1, -1));

        jLabel45.setBackground(new java.awt.Color(204, 255, 255));
        jLabel45.setForeground(new java.awt.Color(204, 255, 255));
        jLabel45.setText("BELAH KETUPAT");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, 10));

        jLabel46.setBackground(new java.awt.Color(204, 255, 255));
        jLabel46.setForeground(new java.awt.Color(204, 255, 255));
        jLabel46.setText("Diagonal 1");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 55, -1));

        jLabel47.setBackground(new java.awt.Color(204, 255, 255));
        jLabel47.setForeground(new java.awt.Color(204, 255, 255));
        jLabel47.setText("LINGKARAN");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel48.setBackground(new java.awt.Color(204, 255, 255));
        jLabel48.setForeground(new java.awt.Color(204, 255, 255));
        jLabel48.setText("Jari-jari");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 20));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 130, 10));
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 55, -1));

        jLabel50.setBackground(new java.awt.Color(204, 255, 255));
        jLabel50.setForeground(new java.awt.Color(204, 255, 255));
        jLabel50.setText("PERSEGI PANJANG");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 130, 10));

        jLabel51.setBackground(new java.awt.Color(204, 255, 255));
        jLabel51.setForeground(new java.awt.Color(204, 255, 255));
        jLabel51.setText("Panjang");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 20));

        jLabel52.setBackground(new java.awt.Color(204, 255, 255));
        jLabel52.setForeground(new java.awt.Color(204, 255, 255));
        jLabel52.setText("Lebar");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 20));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 500, 10));

        jLabel53.setBackground(new java.awt.Color(204, 255, 255));
        jLabel53.setForeground(new java.awt.Color(204, 255, 255));
        jLabel53.setText("Output Hasil Belah Ketupat :");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 150, 120));

        jLabel54.setForeground(new java.awt.Color(204, 255, 255));
        jLabel54.setText("Output Hasil Lingkaran");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 150, 120));

        jLabel55.setForeground(new java.awt.Color(204, 255, 255));
        jLabel55.setText("Output Hasil Persegi Panjang");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 150, 120));

        jLabel56.setBackground(new java.awt.Color(204, 255, 255));
        jLabel56.setForeground(new java.awt.Color(204, 255, 255));
        jLabel56.setText("Diagonal 2");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 55, -1));

        jLabel57.setBackground(new java.awt.Color(204, 255, 255));
        jLabel57.setForeground(new java.awt.Color(204, 255, 255));
        jLabel57.setText("Sisi");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 55, -1));

        jLabel90.setText("HITUNG");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel90)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel90)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 130, -1));

        jLabel91.setText("HITUNG");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel91)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel91)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, -1));

        jLabel92.setText("HITUNG");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel92)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel92)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, -1));
        jPanel2.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 55, -1));
        jPanel2.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 55, -1));

        tampilMenu2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 580, 470));

        bgMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg4.jpg"))); // NOI18N
        tampilMenu2.add(bgMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelHome.add(tampilMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 530));

        tampilMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tampilMenu3MouseEntered(evt);
            }
        });
        tampilMenu3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel58.setText("Menu 3 Form Isian");
        jPanel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel29.setText("Nama");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel30.setText("Jenis Kelamin");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel59.setText("Jurusan");
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel60.setText("Minat");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));
        jPanel3.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 160, -1));

        jRadioButton1.setText("Male");
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jRadioButton2.setText("Female");
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEKNIK INFORMATIKA", "TEKNIK KOMPUTER", "SISTEM KOMPUTER", "\t" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, -1));

        jCheckBox2.setText("Design UI UX");
        jPanel3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jCheckBox3.setText("Programming");
        jPanel3.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jCheckBox4.setText("Game");
        jPanel3.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel61.setText("Area Penempatan");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bandung", "Semarang", "Jakarta", "Yogyakarta", "Surabaya" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList1);

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 160, 90));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 270, -1));

        jLabel62.setText("Output");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane8.setViewportView(jTextArea7);

        jPanel3.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 270, -1));

        tampilMenu3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 320, 470));

        bgMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg4.jpg"))); // NOI18N
        tampilMenu3.add(bgMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelHome.add(tampilMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 530));

        tampilMenu4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51, 50));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(204, 255, 255));
        jLabel63.setText("Menu 4 Edit Profile");
        jPanel4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel64.setForeground(new java.awt.Color(204, 255, 255));
        jLabel64.setText("Username");
        jPanel4.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        jLabel65.setForeground(new java.awt.Color(204, 255, 255));
        jLabel65.setText("Email");
        jPanel4.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        jLabel66.setForeground(new java.awt.Color(204, 255, 255));
        jLabel66.setText("Phone");
        jPanel4.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 20));

        jLabel67.setForeground(new java.awt.Color(204, 255, 255));
        jLabel67.setText("Last Password");
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        jLabel68.setForeground(new java.awt.Color(204, 255, 255));
        jLabel68.setText("New Password");
        jPanel4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 170, -1));
        jPanel4.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, -1));
        jPanel4.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, -1));

        jPasswordField4.setText("jPasswordField4");
        jPanel4.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 170, -1));

        jPasswordField5.setText("jPasswordField4");
        jPanel4.add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, -1));
        jPanel4.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 560, 10));

        jLabel69.setForeground(new java.awt.Color(204, 255, 255));
        jLabel69.setText("Output :");
        jPanel4.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane9.setViewportView(jTextArea8);

        jPanel4.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 520, 140));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel70.setText("Simpan");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel70)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel70)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 170, 20));

        tampilMenu4.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 580, 470));

        bgMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg4.jpg"))); // NOI18N
        tampilMenu4.add(bgMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelHome.add(tampilMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 530));

        tampilAbout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 51, 51, 50));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel71.setText("Menu About");
        jPanel7.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile.jpg"))); // NOI18N
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel32.setForeground(new java.awt.Color(204, 255, 255));
        jLabel32.setText("Nama ");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel72.setForeground(new java.awt.Color(204, 255, 255));
        jLabel72.setText("Email");
        jPanel7.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel73.setForeground(new java.awt.Color(204, 255, 255));
        jLabel73.setText("NIM");
        jPanel7.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel74.setForeground(new java.awt.Color(204, 255, 255));
        jLabel74.setText("TTL");
        jPanel7.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel75.setForeground(new java.awt.Color(204, 255, 255));
        jLabel75.setText("Kelas");
        jPanel7.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel76.setForeground(new java.awt.Color(204, 255, 255));
        jLabel76.setText("Kampus");
        jPanel7.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jLabel77.setForeground(new java.awt.Color(204, 255, 255));
        jLabel77.setText("Instagram");
        jPanel7.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jLabel78.setForeground(new java.awt.Color(204, 255, 255));
        jLabel78.setText(": Muhamad Nurcahya Eko D");
        jPanel7.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jLabel79.setForeground(new java.awt.Color(204, 255, 255));
        jLabel79.setText(": Email");
        jPanel7.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel80.setForeground(new java.awt.Color(204, 255, 255));
        jLabel80.setText(": Bandung, 13-10-1997");
        jPanel7.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel81.setForeground(new java.awt.Color(204, 255, 255));
        jLabel81.setText(": PBO-11");
        jPanel7.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel82.setForeground(new java.awt.Color(204, 255, 255));
        jLabel82.setText(": Unikom");
        jPanel7.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabel83.setForeground(new java.awt.Color(204, 255, 255));
        jLabel83.setText(": Nucahyaeko");
        jPanel7.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel84.setForeground(new java.awt.Color(204, 255, 255));
        jLabel84.setText(": 10116468");
        jPanel7.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel93.setText("App  Version : 1.00");
        jPanel7.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        tampilAbout.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 580, 470));

        bgAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg4.jpg"))); // NOI18N
        tampilAbout.add(bgAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelHome.add(tampilAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 530));

        bgMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background1.jpg"))); // NOI18N
        panelHome.add(bgMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Color awalBtn = new Color(204,204,204);
    Color rubahBtn = new Color(204,204,255);
    Color awalKlik = new Color(204,204,204);
    
    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        panelLogin.setVisible(false);
        panelRegister.setVisible(false);
        panelHome.setVisible(true);
        tampilMenu1.setVisible(false);
        tampilMenu2.setVisible(false);
        tampilMenu3.setVisible(false);
        tampilMenu4.setVisible(false);
        
    }//GEN-LAST:event_btnLoginMouseClicked
    
    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(rubahBtn);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseMoved

    private void btnLoginCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginCreateMouseClicked
        // TODO add your handling code here:
        panelLogin.setVisible(false);
        panelRegister.setVisible(true);
        panelHome.setVisible(false);
    }//GEN-LAST:event_btnLoginCreateMouseClicked

    private void btnLoginCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginCreateMouseEntered
        // TODO add your handling code here:
        btnLoginCreate.setBackground(rubahBtn);
    }//GEN-LAST:event_btnLoginCreateMouseEntered

    private void btnLoginCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginCreateMouseExited
        // TODO add your handling code here:
        btnLoginCreate.setBackground(awalKlik);
    }//GEN-LAST:event_btnLoginCreateMouseExited

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        panelLogin.setVisible(true);
        panelRegister.setVisible(false);
        panelHome.setVisible(false);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        btnBack.setBackground(rubahBtn);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        btnBack.setBackground(awalKlik);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseEntered
        // TODO add your handling code here:
        btnReset.setBackground(rubahBtn);
    }//GEN-LAST:event_btnResetMouseEntered

    private void btnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseExited
        // TODO add your handling code here:
        btnReset.setBackground(awalKlik);
    }//GEN-LAST:event_btnResetMouseExited

    private void btnCreateRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateRegMouseClicked
        // TODO add your handling code here:
        panelLogin.setVisible(true);
        panelRegister.setVisible(false);
        panelHome.setVisible(false);
    }//GEN-LAST:event_btnCreateRegMouseClicked
//////////////////////////////////////////////////
    private void btnCreateRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateRegMouseEntered
        // TODO add your handling code here:
        btnCreateReg.setBackground(awalBtn);
    }//GEN-LAST:event_btnCreateRegMouseEntered

    private void btnCreateRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateRegMouseExited
        // TODO add your handling code here:
        btnCreateReg.setBackground(awalKlik);
    }//GEN-LAST:event_btnCreateRegMouseExited

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        // TODO add your handling code here:
        
        welcome.setVisible(false);
        tampilMenu1.setVisible(true);
        tampilMenu2.setVisible(false);
        tampilMenu3.setVisible(false);
        tampilMenu4.setVisible(false);
        tampilAbout.setVisible(false);
    }//GEN-LAST:event_menu1MouseClicked

    private void menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseEntered
        // TODO add your handling code here:
        menu1.setBackground(rubahBtn);
    }//GEN-LAST:event_menu1MouseEntered

    private void menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseExited
        // TODO add your handling code here:
        menu1.setBackground(awalBtn);
    }//GEN-LAST:event_menu1MouseExited

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        // TODO add your handling code here:
        welcome.setVisible(false);
        tampilMenu1.setVisible(false);
        tampilMenu2.setVisible(true);
        tampilMenu3.setVisible(false);
        tampilMenu4.setVisible(false);
        tampilAbout.setVisible(false);
    }//GEN-LAST:event_menu2MouseClicked

    private void menu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseEntered
        // TODO add your handling code here:
        menu2.setBackground(rubahBtn);
    }//GEN-LAST:event_menu2MouseEntered

    private void menu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseExited
        // TODO add your handling code here:
        menu2.setBackground(awalBtn);
    }//GEN-LAST:event_menu2MouseExited

    private void menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3MouseClicked
        // TODO add your handling code here:
        welcome.setVisible(false);
        tampilMenu1.setVisible(false);
        tampilMenu2.setVisible(false);
        tampilMenu3.setVisible(true);
        tampilMenu4.setVisible(false);
        tampilAbout.setVisible(false);
    }//GEN-LAST:event_menu3MouseClicked

    private void menu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3MouseEntered
        // TODO add your handling code here:
        menu3.setBackground(rubahBtn);
    }//GEN-LAST:event_menu3MouseEntered

    private void menu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3MouseExited
        // TODO add your handling code here:
        menu3.setBackground(awalBtn);
    }//GEN-LAST:event_menu3MouseExited

    private void menu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4MouseClicked
        // TODO add your handling code here:
        welcome.setVisible(false);
        tampilMenu1.setVisible(false);
        tampilMenu2.setVisible(false);
        tampilMenu3.setVisible(false);
        tampilMenu4.setVisible(true);
        tampilAbout.setVisible(false);
    }//GEN-LAST:event_menu4MouseClicked

    private void menu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4MouseEntered
        // TODO add your handling code here:
        menu4.setBackground(rubahBtn);
    }//GEN-LAST:event_menu4MouseEntered

    private void menu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4MouseExited
        // TODO add your handling code here:
        menu4.setBackground(awalBtn);
    }//GEN-LAST:event_menu4MouseExited

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        // TODO add your handling code here:
        welcome.setVisible(false);
        tampilMenu1.setVisible(false);
        tampilMenu2.setVisible(false);
        tampilMenu3.setVisible(false);
        tampilMenu4.setVisible(false);
        tampilAbout.setVisible(true);
    }//GEN-LAST:event_AboutMouseClicked

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
        // TODO add your handling code here:
        About.setBackground(rubahBtn);
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
        // TODO add your handling code here:
        About.setBackground(awalBtn);
    }//GEN-LAST:event_AboutMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        panelLogin.setVisible(true);
        panelRegister.setVisible(false);
        panelHome.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(rubahBtn);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(awalBtn);
    }//GEN-LAST:event_logoutMouseExited

    private void welcomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeMouseEntered
        // TODO add your handling code here:
        tampilMenu1.setVisible(false);
        tampilMenu2.setVisible(false);
        tampilMenu3.setVisible(false);
        tampilMenu4.setVisible(false);
        tampilAbout.setVisible(false);
        
    }//GEN-LAST:event_welcomeMouseEntered

    private void panelLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLoginMouseEntered
        // TODO add your handling code here:
        panelHome.setVisible(false);
        
    }//GEN-LAST:event_panelLoginMouseEntered

    private void tampilMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilMenu1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilMenu1MouseExited

    private void tampilMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilMenu1MouseEntered
        // TODO add your handling code here:
        tampilMenu3.setVisible(false);
    }//GEN-LAST:event_tampilMenu1MouseEntered

    private void tampilMenu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilMenu3MouseEntered
        welcome.setVisible(false);
        tampilMenu1.setVisible(false);
        tampilMenu2.setVisible(false);
        tampilMenu3.setVisible(true);
        tampilMenu4.setVisible(false);
        tampilAbout.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilMenu3MouseEntered

    private void panelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelHomeMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(awalKlik);
    }//GEN-LAST:event_btnLoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JLabel Background2;
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel bgAbout;
    private javax.swing.JLabel bgMenu;
    private javax.swing.JLabel bgMenu1;
    private javax.swing.JLabel bgMenu2;
    private javax.swing.JLabel bgMenu3;
    private javax.swing.JLabel bgMenu4;
    private javax.swing.JLabel bgMenu6;
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel btnCreateReg;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JPanel btnLoginCreate;
    private javax.swing.JPanel btnReset;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    private javax.swing.JPanel menu4;
    private javax.swing.JPanel menuPilihan;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JPanel tampilAbout;
    private javax.swing.JPanel tampilMenu1;
    private javax.swing.JPanel tampilMenu2;
    private javax.swing.JPanel tampilMenu3;
    private javax.swing.JPanel tampilMenu4;
    private javax.swing.JPanel welcome;
    // End of variables declaration//GEN-END:variables
}
